export const languageMaps = {
    program_languages: {
        javascript: "JavaScript",
        typescript: "TypeScript",
        python: "Python",
        java: "Java",
        c: "C",
        cpp: "C++",
        csharp: "C#",
        go: "Go",
        php: "PHP",
        ruby: "Ruby",
        swift: "Swift",
        kotlin: "Kotlin",
        rust: "Rust",
        dart: "Dart",
        scala: "Scala",
        r: "R",
    },
    web_markup: {
        html: "HTML",
        css: "CSS",
        scss: "SCSS / SASS",
        json: "JSON",
        markdown: "Markdown",
    },
    other: {
        bash: "Bash / Shell",
        powershell: "PowerShell",
        sql: "SQL",
        yaml: "YAML",
        xml: "XML",
        dockerfile: "Dockerfile",
        graphql: "GraphQL",
    },
} as const;